# Generated by Django 2.1.2 on 2018-10-18 09:24

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combos', django_mysql.models.EnumField(choices=[('example', 'combo')])),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django_mysql.models.EnumField(choices=[('red', 'Bright Red'), ('green', 'Vibrant Green'), ('blue', 'blue')])),
            ],
        ),
    ]
